services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - sultanshop-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  bot:
    build:
      context: .
    container_name: bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    networks:
      - sultanshop-network
    volumes:
      - . :/app
    restart: unless-stopped

networks:
  sultanshop-network:

volumes:
  postgres_data:
