"""Добавил поле seller в модель Product

Revision ID: 0d9402bf7f16
Revises: 206f347b9199
Create Date: 2025-04-08 11:30:40.471428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9402bf7f16'
down_revision: Union[str, None] = '206f347b9199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'seller')
    # ### end Alembic commands ###
