"""правки в таблице с заказами

Revision ID: 162c3da827e8
Revises: 7d5fa61918b6
Create Date: 2025-05-15 20:20:40.309424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162c3da827e8'
down_revision: Union[str, None] = '7d5fa61918b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliverer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'deliverer', ['deliverer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'deliverer_id')
    # ### end Alembic commands ###
