"""внешний ключ deliverer_id заменен на deliverer_telegram_id доп. правка

Revision ID: 750c1f0574c4
Revises: c55374e865c2
Create Date: 2025-05-14 14:51:40.176145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750c1f0574c4'
down_revision: Union[str, None] = 'c55374e865c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
