"""правки в таблице с заказами

Revision ID: 7d5fa61918b6
Revises: 611e5f325069
Create Date: 2025-05-15 20:14:03.494707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5fa61918b6'
down_revision: Union[str, None] = '611e5f325069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_deliverer_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'deliverer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliverer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_deliverer_id_fkey', 'order', 'deliverer', ['deliverer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
