"""в Таблицу Product добавлено поле unavailable_description

Revision ID: 7f923a0018d5
Revises: ce17823c7aab
Create Date: 2025-06-17 01:55:55.075210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f923a0018d5'
down_revision: Union[str, None] = 'ce17823c7aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unavailable_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unavailable_description')
    # ### end Alembic commands ###
