"""добавлено поле is_active в модель deliverer

Revision ID: 890b453db254
Revises: 6d815da84186
Create Date: 2025-05-12 22:57:19.637048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890b453db254'
down_revision: Union[str, None] = '6d815da84186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverer', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverer', 'is_active')
    # ### end Alembic commands ###
