"""Добавленна новая модель seller

Revision ID: a632472fca3c
Revises: 0d9402bf7f16
Create Date: 2025-04-09 10:20:59.752269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a632472fca3c'
down_revision: Union[str, None] = '0d9402bf7f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'seller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'quantity')
    op.drop_column('product', 'seller_id')
    op.drop_table('sellers')
    # ### end Alembic commands ###
