"""внешний ключ deliverer_id заменен на deliverer_telegram_id]

Revision ID: c55374e865c2
Revises: de8256ec0233
Create Date: 2025-05-14 14:48:48.430616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55374e865c2'
down_revision: Union[str, None] = 'de8256ec0233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliverer_telegram_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('order_deliverer_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'deliverer', ['deliverer_telegram_id'], ['telegram_id'], ondelete='SET NULL')
    op.drop_column('order', 'deliverer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliverer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_deliverer_id_fkey', 'order', 'deliverer', ['deliverer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order', 'deliverer_telegram_id')
    # ### end Alembic commands ###
