"""Добавил поле закупочная цена

Revision ID: cbc71e3caaf7
Revises: 8e5541cdc101
Create Date: 2025-04-11 06:00:30.114329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc71e3caaf7'
down_revision: Union[str, None] = '8e5541cdc101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('purchase_price', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'purchase_price')
    # ### end Alembic commands ###
