"""исправил колличество символов в модели seller для воля phone

Revision ID: cf306a56b41f
Revises: cbc71e3caaf7
Create Date: 2025-04-18 09:43:49.728069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf306a56b41f'
down_revision: Union[str, None] = 'cbc71e3caaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'phone',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###
