"""Удалены координаты, изменены статусы

Revision ID: d9978d9f224f
Revises: 5b34c3518bdc
Create Date: 2025-04-02 20:05:56.863642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9978d9f224f'
down_revision: Union[str, None] = '5b34c3518bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE \"order\" ALTER COLUMN status TYPE order_status USING status::order_status")
    op.drop_column('order', 'latitude')
    op.drop_column('order', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'longitude')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('order', 'status',
               existing_type=sa.Enum('оформлен', 'в работе', 'Выполнен', name='order_status'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
