"""Добавлен внешний ключ для deliverer_id

Revision ID: de8256ec0233
Revises: 2e8d8183d6ad
Create Date: 2025-05-13 17:20:39.402132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8256ec0233'
down_revision: Union[str, None] = '2e8d8183d6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliverer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'deliverer', ['deliverer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'deliverer_id')
    # ### end Alembic commands ###
