"""Убрал поле quantiy и добавил is_available в таблицу Product

Revision ID: f40cfc020bf2
Revises: cf306a56b41f
Create Date: 2025-04-29 12:55:56.419408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40cfc020bf2'
down_revision: Union[str, None] = 'cf306a56b41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'is_available')
    # ### end Alembic commands ###
